name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
      - '**.jsx'
      - '**.json'
      - '**.css'
      - 'public/**'
      - 'components/**'
      - 'pages/**'
      - 'styles/**'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/website/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
          elif [ -f "${{ github.workspace }}/website/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        working-directory: ./website
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build Next.js site
        working-directory: ./website
        run: ${{ steps.detect-package-manager.outputs.runner }} next build

      - name: Export static site
        working-directory: ./website
        run: ${{ steps.detect-package-manager.outputs.runner }} next export

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        id: deploy
        working-directory: ./website
        run: |
          export SURGE_DOMAIN="pr-${{ github.event.pull_request.number }}-webtres.surge.sh"
          surge ./out $SURGE_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
          echo "url=https://$SURGE_DOMAIN" >> $GITHUB_OUTPUT
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = '${{ steps.deploy.outputs.url }}';
            const prNumber = context.issue.number;
            
            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('🚀 Preview Deployment')
            );
            
            const body = `## 🚀 Preview Deployment
            
            Your preview deployment is ready!
            
            ✅ **Preview URL:** ${url}
            
            ---
            
            <sub>Updated for commit: ${context.sha.substring(0, 7)}</sub>`;
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: body
              });
            }

